extends:
  # - "./markuplint-config/index.js"
  - "markuplint:recommended"
specs:
  \.[jt]sx?$: "@markuplint/react-spec"
parser:
  \.[jt]sx?$: "@markuplint/jsx-parser"
# nodeRules:
#   - selector: "script[src^='https://']"
#     rules:
#       required-attr: "外部リソースを読み込むのはNGです"
rules:
  invalid-attr:
    options:
      allowAttrs:
        - 'popovertarget'
